/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_BRMicro_SerialPort */

#ifndef _Included_com_BRMicro_SerialPort
#define _Included_com_BRMicro_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_BRMicro_SerialPort
 * Method:    switch2channel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_switch2channel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    zigbeepoweron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_zigbeepoweron
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    zigbeepoweroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_zigbeepoweroff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    scanerpoweron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_scanerpoweron
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    scanerpoweroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_scanerpoweroff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    psampoweron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_psampoweron
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    psampoweroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_psampoweroff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    scanertrigeron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_scanertrigeron
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    scanertrigeroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_scanertrigeroff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    power3v3on
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_power3v3on
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    power3v3off
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_power3v3off
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    rfidPoweron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_rfidPoweron
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    rfidPoweroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_rfidPoweroff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    usbOTGpowerOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_usbOTGpowerOn
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    usbOTGpowerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_usbOTGpowerOff
  (JNIEnv *, jobject);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    setGpioHigh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_setGpioHigh
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_BRMicro_SerialPort
 * Method:    setGpioLow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_BRMicro_SerialPort_setGpioLow
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
